apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shubhamgupta1096/auth
          env:
            - name: JWT_KEY #variable name by which value will be accessible inside the application
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # name of the secret
                  key: JWT_KEY # key inside the secret whose value will we want to use
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
